version: "3.9"

services:

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - $MONGO_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
  backend:
    image: "registry.gitlab.com/i3-market/code/wp5/industry-4_0-manufacturing/react-rating-component:dev"
    ports:
     - $BACKEND_PORT:$BACKEND_PORT
    environment:
     - BACKEND_PORT=$BACKEND_PORT
     - MONGO_PASSWORD=$MONGO_PASSWORD
     - MONGO_USER=$MONGO_USER
     - MONGO_URL=$MONGO_URL
     - OIDC_URL=$OIDC_URL
     - JWKS_PATH=$JWKS_PATH
     - NOTIFICATION_URL=$NOTIFICATION_URL
     - AGREEMENT_URL=$AGREEMENT_URL
    links:
     - mongo:mongo